import os

AWS_ACCESS_KEY = os.environ["AWS_ACCESS_KEY"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
AWS_REGION = os.environ["AWS_REGION"]
AWS_NEPTUNE_HOST = os.environ["AWS_NEPTUNE_HOST"]
AWS_NEPTUNE_PORT = os.getenv("AWS_NEPTUNE_PORT", 8182)
AWS_NEPTUNE_QUERY_TIMEOUT = os.getenv("AWS_NEPTUNE_QUERY_TIMEOUT", 20)
